# Generated by Django 3.0.8 on 2020-09-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='entry',
            new_name='entry_text',
        ),
    ]
